### ISSUE TITLE
Stone cutter addition + craft tweaker recipes

### ISSUE THREAD

**Issue by PizzaPolice** [reuy/Freelancer-Initiative#111]
https://www.curseforge.com/minecraft/mc-mods/future-mc
Has stone cuttter (+ some other it's probably fine shit)

Probably double smooth stone (or dust added stone)
tooltop: "Processing this stone has made it in flux and a bit of excitiation could transform it in to something else in the stonecutters bench"
Maybe flavor text basalt/marble in to "artificail baslat/marble, or don't"

**Comment by reuy** [comment]
- [x] Quarried Stone
- [x] Abyssal Stone
- [x] Limestone
- [x] Diorite
- [x] Granite
- [x] Andesite
