### ISSUE TITLE
Refined storage cost rework

### ISSUE THREAD

**Issue by PizzaPolice** [reuy/Freelancer-Initiative#155]
Patterns shoudl not use 3 iron each
Quartz "plate problem" (silicon and quartz iron both use quartz, standard iron plate problem)
Slime ball is an unreliable cost other htan specific chese + is core to everything
Possble magister help required rework later

Replace processor binding with plastic
Replace silicon used with raw quartz

Replace all quartz infused iron with plastic
Replace machine casing with plastic outside one invar block in middle

Replace cutting tool tip with quartz or iron

Remove raw circuits and silicon from JEI

**Comment by reuy** [comment]
1. Global replace all instances of Quartz infused with plastic.
2. Replace the Machine Case's center block with: ore:circuitAdvanced
4. Replace the Cutting tool's tip with quartz
