### ISSUE TITLE
Feeding Troughs

### ISSUE THREAD

**Issue by reuy** [reuy/Freelancer-Initiative#264]
We have 2 feeding trough blocks, and need to decide whether to ditch one or reframe one as an upgraded form of the other.

**Comment by PizzaPolice** [comment]
Remove quark, people will be confused why it's eating everything for marginal gain vs blockheads "only use on cloning cooldown" is more intuitive

**Comment by PizzaPolice** [comment]
WONTFIX BLOCKEHADS REMOVED
