### ISSUE TITLE
ic2 rubber not compatible 

### ISSUE THREAD

**Issue by reuy** [reuy/Freelancer-Initiative#267]
IC2 rubber seems difficult to obtain and is not oredicted with other rubber types. This renders the IC2 tree artificially hard to enter.

**Comment by PizzaPolice** [comment]
IC2 does not use json recipes which fucks with using craft tweaker to edit recipes, i can add a recipe to convert foregoing rubber to IC2 rubber (Vulkanization?) but can not otherwise mass edit IC2 recipes

Proposal: recipe sulfur + rubber -> Ic2 rubber, sulfur is not mass produceable

**Comment by PizzaPolice** [comment]
EXTRACTOR DRY _ RUBBER -> IC2 RUBBER CONVERSION, FORCED TO MAKE RUBBER THE INTENDED IC2 WAY BEFORE CONVERSION
