### ISSUE TITLE
Removal Candidates

### ISSUE THREAD

**Issue by PizzaPolice** [reuy/Freelancer-Initiative#294]
Immersive aircraft (tentataive problbay)

Mana and artifice (GOODBYE)

Simple quarry (very very simple, degeneratively inefficient, incentivizes property value loss, create has more "fun" ways to do mass mining, the usual chunk loading issues)

Little logistics (create trains better for land transport, sea transport you can use fake rails for your paths anyway)

Create cafe (RECIPE BLOAAAAATTT + COLONST TECHNICAIIN HYBRID ONLY)

MEADOW (BLOAT)

Stargate journey (BORING LOGISTICS, JANK)

Small ships (Valky skies clockwork + create exist)

Simply swords (conflict with aprtans armory)

Mining gadgets (kind of jank, maybe)

IC2 (lower interaciton with everything else, unmoddable recipes, doesn't integrate with unifyores, breaks with patchouli recipe display)

Industrial foregoing (power scale is more big timmy than sanity of others, shittry pink slime item gate, aesthetics don't fit with other mods, more "boring" versions of doing the same thing create does

Mo than enough guns (too "FPS"-ey and broken, sound design doesn't fit, adds duplicate sulfur ore, non abstracted gun names)
just enough guns (sound effects seem muted, overlaps with base game guns, power creeps things toward soldier)

**Comment by reuy** [comment]
Mana and Artifice

**Comment by reuy** [comment]
- [ ] - Tectonic (Before next flight) - Change to Terralith to compare the two
- [ ] - Iron Chests - Replace with [Iron Chests Restocked](https://www.curseforge.com/minecraft/mc-mods/ironchests)

**Comment by PizzaPolice** [comment]
COMPLETE IN 1.20 BRANCH
